### ISSUE TITLE
Run common role with empty common_nameservers variable

### ISSUE THREAD

**Issue by dmrub** [robertdebock/ansible-role-common#2]
## Proposed feature

I would like to be able to run common role without changing nameservers, but it is currently not possible because I get the following error message when I set the variable common_nameservers to an empty array:
`Fatal: [asr-vm-rundeck]: FAILED! => {"assertion": "common_nameservers | length > 0", "changed": false, "evaluated_to": false, "msg": "Assertion failed"}`

## Rationale

Why is this feature required?

Not in all cases it is desired to replace name servers.

**Comment by robertdebock** [comment]
Good find, thanks! Merges your PR. Will release a new version in a bit.
